global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "scan-quality-api"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["mlops-control-plane:30081"]

  - job_name: "scan-drift-monitor"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["mlops-control-plane:30082"]